spring:
  ai:
    chat:
      observations:
        include-completion: true
        include-prompt: true
        include-error-logging: true
      client:
        observations:
          include-input: true
    openai:
      api-key: INSERT_YOUR_KEY_HERE
      chat:
        enabled: true
        options:
          model: gpt-4o-mini
  docker:
    compose:
      lifecycle-management: start_only

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
